"""Hand-written teaching content layered on top of phonics_toc.xlsx.

Keyed by TOC page number (1-42).
"""

# 발음 팁 — shown in the sound box on every A page.
TIPS = {
    1: "짧은 모음 5개. a는 '애', e는 '에', i는 짧은 '이', o는 입을 크게 '아', u는 '어'. 단어의 첫소리로 들어 봐요.",
    2: "t는 혀끝을 윗잇몸에 대고 바람만 '트', n은 혀를 댄 채 코로 '은', m은 입술을 붙이고 '음'.",
    3: "s는 바람 새는 '스—', p는 입술을 터뜨리며 바람만 '프', d는 혀끝을 대고 목을 울려 '드'.",
    4: "딱딱한 g는 '그', 딱딱한 c는 k와 같은 '크'. r은 입술을 동그랗게 하고 혀를 말아 '르'.",
    5: "b는 입술을 터뜨리며 목을 울려 '브', h는 손에 입김을 부는 '흐', l은 혀끝을 윗잇몸에 붙이고 '을'.",
    6: "f는 윗니를 아랫입술에 대고 바람 '프—', k는 '크', w는 입술을 쭉 내밀고 '워'.",
    7: "j는 '즈'(jam=잼), v는 윗니를 아랫입술에 대고 떨리게 '브—', 자음 y는 '이'로 미끄러지는 소리(yes=예스).",
    8: "z는 벌 소리 '즈—', x는 단어 끝에서 '크스'(box), qu는 늘 함께 다니며 '크w'(quiz=퀴즈).",
    9: "sh는 '쉿!' 조용히 하라는 소리, ch는 기차 '칙칙'의 '취'. 둘 다 입술을 앞으로 내밀어요.",
    10: "무성 th는 혀를 이 사이에 살짝 물고 바람만(thin), 유성 th는 같은 모양에 목을 떨어요(this).",
    11: "tch는 ch와 같은 '취' 소리. 짧은 모음 바로 뒤, 단어 끝에서는 tch로 써요(catch).",
    12: "ck는 '크' — 짧은 모음 바로 뒤 끝에서 써요(duck). ng는 코로 울리는 '응'(king).",
    13: "wh는 w와 같은 '워'(when), ph는 f와 같은 '프'(phone). 이미 아는 소리를 다른 철자로 써요!",
    14: "FLSZ 규칙: 짧은 모음 뒤 끝의 f, l, s, z는 두 번 써요(off, bell, boss, buzz).",
    15: "두 자음을 한 번에 빠르게! 사이에 '으'를 넣지 않아요(black ≠ 블랙 → bl-a-ck).",
    16: "끝 자음군은 두 소리를 모두 내요(ha-n-d). 세 글자 자음군은 세 소리를 쭉 이어요(s-t-r).",
    17: "열린 음절: 음절이 모음으로 끝나면 모음이 자기 이름을 말해요(me=미, go=고우).",
    18: "Magic e: 끝의 e는 소리가 없지만 앞 모음이 자기 이름을 말하게 해요(kit → kite).",
    19: "ai와 ay는 둘 다 '에이'. 단어 중간엔 ai(rain), 끝엔 ay(day).",
    20: "ee와 ea는 둘 다 길게 '이—'(bee, sea).",
    21: "oa와 ow는 '오우'. 중간엔 주로 oa(boat), 끝엔 ow(snow).",
    22: "igh, ie, 짧은 단어 끝의 y는 모두 '아이'(high, pie, my).",
    23: "두 음절 이상인 단어 끝의 y는 '이'(happy, baby).",
    24: "oo, ew, ue, ui는 모두 길게 '우—'(moon, new, blue, fruit).",
    25: "짧은 oo는 '우'를 짧고 가볍게(book, look).",
    26: "eigh는 '에이'(eight). gh는 소리가 나지 않아요.",
    27: "ar은 입을 크게 벌린 '아' 다음에 혀를 말아요(car).",
    28: "or와 ore는 '오어r'(corn, more). ore의 e는 소리가 없어요.",
    29: "er, ir, ur은 모두 같은 '어r'(her, bird, fur). 철자만 달라요.",
    30: "oi와 oy는 '오이'. 중간엔 oi(coin), 끝엔 oy(boy).",
    31: "ou와 ow는 다쳤을 때 '아우!'(out, cow).",
    32: "au와 aw는 입을 동그랗게 '오—'(haul, saw). 끝에는 aw를 써요.",
    33: "c, g 뒤에 e·i·y가 오면 부드러워져요: c는 '스'(city), g는 '즈'(gem).",
    34: "kn의 k, wr의 w, mb의 b, gn의 g는 숨은 글자 — 소리가 나지 않아요(knee, write, comb, gnat).",
    35: "강세 없는 모음은 힘을 빼고 '어'처럼 약하게(about = 어-바웃). 사전의 ə 기호예요.",
    36: "음절 6유형을 알면 긴 단어도 쪼개 읽을 수 있어요. 자음+le는 '을'로 끝나요(ta-ble).",
    37: "-s/-es는 '여러 개', -ed는 '~했다', -ing는 '~하는 중'. -ed는 t·d·id 세 가지 소리가 나요.",
    38: "-er은 '더 ~한', -est는 '가장 ~한', -ly는 '~하게'. 짧은 모음 뒤엔 자음을 겹쳐요(big → bigger).",
    39: "un-은 '아닌·반대로', re-는 '다시', dis-는 '반대'. 접두사 + 원래 단어로 쪼개 읽어요.",
    40: "mis-는 '잘못', pre-는 '미리'(mis + take, pre + view).",
    41: "-ful은 '가득한', -less는 '없는', -ness는 '~함'(help + ful, care + less, kind + ness).",
    42: "-tion·-sion은 '션', -ture는 '쳐'. 단어 끝에서 한 덩어리로 읽어요(sta-tion, pic-ture).",
}

# 원본 목차에 없던 소리를 채우는 보충 단어 (★ 표시).
SUPPLEMENT = {
    4: ["rag", "red", "rip", "rug"],
    5: ["hat", "hen", "lap", "log"],
    6: ["web", "wet", "wig", "win"],
    7: ["yes", "yet", "yak", "yum"],
    8: ["zip", "zap", "quit", "quiz"],
    13: ["graph", "photo", "phone", "dolphin"],
    15: ["crab", "drum", "frog", "trip", "skip", "snap", "stop", "swim"],
    16: ["split", "strap", "scrub", "sprint", "thrill", "shrub", "squid"],
    19: ["rain", "tail"],
    21: ["snow", "grow", "slow", "bowl"],
    22: ["my", "fly", "cry", "sky"],
    24: ["moon", "food", "fruit", "suit"],
    31: ["loud", "cloud", "mouth"],
    32: ["fault", "launch"],
    33: ["gem", "gym", "cage", "page"],
    34: ["wrap", "wrist", "wreck", "write"],
    37: ["jumped", "played", "jumping", "playing"],
    38: ["quickly", "slowly", "kindly", "softly"],
    39: ["redo", "retell", "dislike", "disagree"],
    40: ["preview", "preheat", "pretest", "preschool"],
    41: ["careless", "helpless", "kindness", "sadness"],
    42: ["mission", "tension", "picture", "nature"],
}

# 뜻 연결 — word: Korean gloss.
GLOSS = {
    "ant": "개미", "egg": "달걀", "ink": "잉크", "ox": "황소", "up": "위로", "apple": "사과",
    "umbrella": "우산", "igloo": "이글루", "otter": "수달",
    "man": "남자", "mat": "매트", "net": "그물", "nut": "견과", "mom": "엄마", "it": "그것",
    "dad": "아빠", "dam": "댐", "map": "지도", "dip": "살짝 담그다", "dot": "점", "us": "우리를",
    "cap": "모자", "cat": "고양이", "cup": "컵", "dog": "개", "dig": "땅을 파다", "cut": "자르다",
    "can": "깡통", "red": "빨간", "rug": "깔개", "cod": "대구(생선)",
    "bag": "가방", "bed": "침대", "bib": "턱받이", "bug": "벌레", "bus": "버스", "hat": "모자",
    "hen": "암탉", "log": "통나무", "bad": "나쁜", "bat": "박쥐",
    "fan": "선풍기", "fig": "무화과", "fin": "지느러미", "fog": "안개", "fun": "재미",
    "kid": "아이", "web": "거미줄", "wig": "가발", "elk": "엘크(큰 사슴)",
    "jam": "잼", "jet": "제트기", "job": "일, 직업", "jug": "주전자", "van": "승합차",
    "vet": "수의사", "yes": "네", "jog": "천천히 달리다",
    "box": "상자", "fix": "고치다", "fox": "여우", "six": "여섯", "wax": "밀랍", "zip": "지퍼를 잠그다",
    "quiz": "퀴즈", "ax": "도끼",
    "cash": "현금", "chat": "수다 떨다", "chin": "턱", "chip": "감자칩", "chop": "잘게 썰다",
    "dish": "접시", "fish": "물고기", "ship": "배",
    "bath": "목욕", "math": "수학", "moth": "나방", "path": "오솔길", "thin": "얇은",
    "batch": "한 묶음", "catch": "잡다", "ditch": "도랑", "fetch": "가져오다", "hatch": "부화하다",
    "match": "성냥", "watch": "손목시계",
    "back": "등", "bang": "쾅", "deck": "갑판", "duck": "오리", "king": "왕", "lock": "자물쇠",
    "when": "언제", "whip": "채찍", "which": "어느 것", "phone": "전화기", "photo": "사진",
    "dolphin": "돌고래",
    "ball": "공", "bell": "종", "boss": "사장님", "doll": "인형", "cuff": "소맷부리",
    "fizz": "보글보글 거품",
    "black": "검은", "blot": "얼룩", "blend": "섞다", "clap": "손뼉 치다", "flag": "깃발",
    "crab": "게", "drum": "북", "frog": "개구리", "swim": "수영하다",
    "hand": "손", "land": "땅", "sand": "모래", "tent": "텐트", "bent": "구부러진",
    "pink": "분홍색", "bank": "은행",
    "me": "나를", "we": "우리", "he": "그", "she": "그녀", "go": "가다", "no": "아니요",
    "bake": "굽다", "cake": "케이크", "cave": "동굴", "date": "날짜", "game": "게임",
    "bike": "자전거", "kite": "연", "five": "다섯",
    "day": "날, 낮", "hay": "건초", "pay": "돈을 내다", "say": "말하다", "rain": "비", "tail": "꼬리",
    "bee": "벌", "eat": "먹다", "sea": "바다", "see": "보다", "tea": "차(마시는 차)",
    "oak": "참나무", "oat": "귀리", "boat": "배", "coat": "외투", "foam": "거품", "goat": "염소",
    "road": "길", "soap": "비누", "snow": "눈",
    "pie": "파이", "tie": "넥타이", "high": "높은", "night": "밤", "light": "빛", "lie": "거짓말",
    "happy": "행복한", "puppy": "강아지", "baby": "아기", "funny": "웃긴", "sunny": "화창한",
    "candy": "사탕", "city": "도시",
    "dew": "이슬", "few": "적은", "new": "새로운", "blue": "파란", "moon": "달", "fruit": "과일",
    "cue": "신호", "hue": "색조", "due": "~하기로 된",
    "book": "책", "cook": "요리하다", "foot": "발", "good": "좋은", "hook": "갈고리",
    "look": "보다", "hood": "모자(후드)",
    "eight": "여덟(8)", "neigh": "히힝(말 울음)", "weigh": "무게를 달다", "eighty": "여든(80)",
    "sleigh": "썰매",
    "arm": "팔", "car": "자동차", "far": "먼", "jar": "병, 단지", "bark": "짖다", "star": "별",
    "farm": "농장",
    "born": "태어난", "cord": "끈", "core": "속, 심", "corn": "옥수수", "fork": "포크",
    "horn": "뿔", "more": "더 많이",
    "fir": "전나무", "fur": "털", "her": "그녀의", "bird": "새", "girl": "소녀", "sir": "선생님(호칭)",
    "boy": "소년", "joy": "기쁨", "oil": "기름", "toy": "장난감", "coin": "동전", "soy": "콩",
    "cow": "소", "how": "어떻게", "now": "지금", "out": "밖으로", "owl": "부엉이", "town": "마을",
    "jaw": "턱", "law": "법", "paw": "동물 발", "raw": "날것의", "saw": "톱", "claw": "발톱",
    "ice": "얼음", "cent": "센트(동전)", "face": "얼굴", "race": "경주", "rice": "쌀, 밥",
    "comb": "빗", "gnat": "날파리", "gnaw": "갉아먹다", "knee": "무릎", "knot": "매듭",
    "know": "알다", "write": "쓰다", "wrap": "포장하다",
    "about": "~에 대하여", "sofa": "소파", "zebra": "얼룩말", "banana": "바나나", "pencil": "연필",
    "lemon": "레몬", "animal": "동물",
    "table": "탁자",
    "cats": "고양이들", "dogs": "개들", "runs": "달린다", "hats": "모자들", "cups": "컵들",
    "boxes": "상자들",
    "faster": "더 빠른", "fastest": "가장 빠른", "bigger": "더 큰", "biggest": "가장 큰",
    "taller": "키가 더 큰",
    "unhappy": "불행한", "unlock": "잠금을 풀다", "undo": "되돌리다", "unfair": "불공평한",
    "unkind": "불친절한",
    "mistake": "실수", "misread": "잘못 읽다", "misplace": "엉뚱한 데 두다",
    "misspell": "철자를 틀리다", "mislead": "잘못 이끌다",
    "helpful": "도움이 되는", "careful": "조심하는", "useful": "쓸모 있는", "joyful": "기쁜",
    "playful": "장난기 많은",
    "action": "행동", "station": "역", "nation": "나라", "motion": "움직임", "section": "부분",
    "question": "질문",
}

# 문장 완성 — (sentence with ___, answer). Both answers + one distractor make the word bank.
SENTENCES = {
    1: [("An ___ is a little bug.", "ant"), ("The hen sat on an ___.", "egg")],
    2: [("The cat sat on the ___.", "mat"), ("Mom has a big ___.", "net")],
    3: [("My ___ is big and tall.", "dad"), ("Look at the ___!", "map")],
    4: [("The ___ is on the mat.", "cat"), ("I have a red ___.", "cap")],
    5: [("I go to ___ at nine.", "bed"), ("A ___ is on the rug.", "bug")],
    6: [("Turn on the ___.", "fan"), ("A spider has a ___.", "web")],
    7: [("I like ___ on my bun.", "jam"), ("The ___ is fast.", "jet")],
    8: [("Put it in the ___.", "box"), ("Dad can ___ it.", "fix")],
    9: [("A ___ can swim.", "fish"), ("I eat a ___.", "chip")],
    10: [("I take a ___.", "bath"), ("I like ___ class.", "math")],
    11: [("Can you ___ the ball?", "catch"), ("Look at my ___.", "watch")],
    12: [("The ___ says quack.", "duck"), ("The ___ has a crown.", "king")],
    13: [("___ is your birthday?", "When"), ("I talk on the ___.", "phone")],
    14: [("Kick the ___.", "ball"), ("Ring the ___.", "bell")],
    15: [("I ___ my hands.", "clap"), ("The ___ can hop.", "frog")],
    16: [("Raise your ___.", "hand"), ("We dig in the ___.", "sand")],
    17: [("___ is my friend.", "She"), ("Can ___ go?", "we")],
    18: [("Mom can ___ a cake.", "bake"), ("I fly a ___.", "kite")],
    19: [("It is a sunny ___.", "day"), ("The ___ is wet.", "rain")],
    20: [("A ___ can sting.", "bee"), ("We swim in the ___.", "sea")],
    21: [("We sail in a ___.", "boat"), ("Put on your ___.", "coat")],
    22: [("I eat apple ___.", "pie"), ("Turn on the ___.", "light")],
    23: [("I am so ___!", "happy"), ("The ___ can bark.", "puppy")],
    24: [("I have a ___ toy.", "new"), ("The sky is ___.", "blue")],
    25: [("I read a ___.", "book"), ("___ at me!", "Look")],
    26: [("I am ___ years old.", "eight"), ("A horse can ___.", "neigh")],
    27: [("Dad drives a ___.", "car"), ("The dog can ___.", "bark")],
    28: [("I eat ___.", "corn"), ("Can I have ___?", "more")],
    29: [("The ___ can fly.", "bird"), ("The ___ has a pink dress.", "girl")],
    30: [("The ___ has a toy.", "boy"), ("The ___ is hot in the pan.", "oil")],
    31: [("The ___ says moo.", "cow"), ("The ___ says hoo.", "owl")],
    32: [("The dog has a big ___.", "paw"), ("I ___ a cat.", "saw")],
    33: [("I live in a big ___.", "city"), ("Wash your ___.", "face")],
    34: [("I hurt my ___.", "knee"), ("I ___ my hair.", "comb")],
    35: [("A monkey likes a ___.", "banana"), ("I write with a ___.", "pencil")],
    36: [("Put the cup on the ___.", "table"), ("I eat an ___.", "apple")],
    37: [("Two ___ sit on the mat.", "cats"), ("The dog ___ fast.", "runs")],
    38: [("A bus is ___ than a car.", "bigger"), ("He is the ___ in my class.", "fastest")],
    39: [("I feel ___ today.", "unhappy"), ("Please ___ the door.", "unlock")],
    40: [("I made a ___.", "mistake"), ("Do not ___ the word.", "misspell")],
    41: [("Be ___ on the road.", "careful"), ("This is a ___ tool.", "useful")],
    42: [("We wait at the ___.", "station"), ("Can I ask a ___?", "question")],
}

# 소리 분류 columns (pages with more than one spelling). Others use 소리 찾기 O/X.
SORT = {
    1: ["a", "e", "i", "o", "u"],
    9: ["sh", "ch"],
    12: ["ck", "ng"],
    13: ["wh", "ph"],
    14: ["ss", "ll", "ff", "zz"],
    15: ["l 블렌드", "r 블렌드", "s 블렌드"],
    16: ["끝 자음군", "3글자 자음군"],
    18: ["a_e", "i_e", "o_e", "u_e"],
    19: ["ai", "ay"],
    20: ["ee", "ea"],
    21: ["oa", "ow"],
    22: ["igh", "ie", "y"],
    24: ["oo", "ew", "ue", "ui"],
    28: ["or", "ore"],
    29: ["er", "ir", "ur"],
    30: ["oi", "oy"],
    31: ["ou", "ow"],
    32: ["au", "aw"],
    33: ["soft c", "soft g"],
    34: ["kn", "wr", "mb", "gn"],
    37: ["-s", "-es", "-ed", "-ing"],
    38: ["-er", "-est", "-ly"],
    39: ["un-", "re-", "dis-"],
    40: ["mis-", "pre-"],
    41: ["-ful", "-less", "-ness"],
    42: ["-tion", "-sion", "-ture"],
}

# 음절 나누기 for pages without a spelling rule to split on.
SYLLABLES = {
    "about": ["a", "bout"], "sofa": ["so", "fa"], "zebra": ["ze", "bra"],
    "banana": ["ba", "na", "na"], "pencil": ["pen", "cil"], "problem": ["prob", "lem"],
    "animal": ["an", "i", "mal"], "lemon": ["lem", "on"],
    "table": ["ta", "ble"], "apple": ["ap", "ple"], "cake": ["cake"], "rain": ["rain"],
    "car": ["car"], "cat": ["cat"], "me": ["me"],
}
